repos:
  - repo: local
    hooks:
      - id: biome-check
        name: biome-check
        entry: node scripts/check_style.js
        language: system
        files: '\\.(json|css)$'
        pass_filenames: true

      - id: cspell
        name: spelling
        entry: python3 scripts/spellcheck.py
        language: system
        files: '\\.(md|MD|txt)$'
        pass_filenames: true

      - id: secretlint
        name: secret-scan
        entry: python3 scripts/secret_scan.py
        language: system
        pass_filenames: true

      - id: cargo-sort
        name: cargo-sort
        entry: python3 scripts/cargo_sort_check.py
        language: system
        pass_filenames: false

      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check
        pass_filenames: false

      - id: clippy
        name: clippy
        language: system
        types: [file, rust]
        entry: cargo clippy --bins --tests --examples --all -- -D rust_2018_idioms -D warnings
        pass_filenames: false

      - id: test
        name: test
        language: system
        types: [file, rust]
        entry: cargo test --workspace
        pass_filenames: false
