[build]
target = "./index.html"
wasm-bindgen = "0.2.92"

[watch]
ignore = ["./src-tauri"]

[serve]
port = 1420
open = false

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "src/input.css", "-o", "dist/output.css"]
