[default]
extend-ignore-words = [
    "9renpoto",
    "appindicator",
    "Avenir",
    "bindgen",
    "cdylib",
    "clippy",
    "dtolnay",
    "ededed",
    "evenodd",
    "fbca",
    "grcov",
    "icns",
    "leptos",
    "libayatana",
    "librsvg",
    "libwebkit",
    "libxdo",
    "LSUI",
    "octocat",
    "profraw",
    "reviewdog",
    "rlib",
    "RUSTFLAGS",
    "serde",
    "staticlib",
    "tauri",
    "TAURI",
    "xlink"
]