[default.extend-words]
"9renpoto" = "9renpoto"
appindicator = "appindicator"
Avenir = "Avenir"
bindgen = "bindgen"
cdylib = "cdylib"
clippy = "clippy"
dtolnay = "dtolnay"
ededed = "ededed"
evenodd = "evenodd"
fbca = "fbca"
grcov = "grcov"
icns = "icns"
leptos = "leptos"
libayatana = "libayatana"
librsvg = "librsvg"
libwebkit = "libwebkit"
libxdo = "libxdo"
LSUI = "LSUI"
octocat = "octocat"
profraw = "profraw"
reviewdog = "reviewdog"
rlib = "rlib"
RUSTFLAGS = "RUSTFLAGS"
serde = "serde"
staticlib = "staticlib"
tauri = "tauri"
TAURI = "TAURI"
xlink = "xlink"