name: "Check spelling"
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: streetsidesoftware/cspell-action@v6
        with:
          files: "*.{rs,ts,tsx,md}"
          incremental_files_only: false
