name: Secretlint
on: push
permissions:
  contents: read
jobs:
  test:
    name: "Secretlint"
    runs-on: ubuntu-22.04
    container: secretlint/secretlint:v8.1.0
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Lint with Secretlint
        run: secretlint "**/*"
